export type MealType = "breakfast" | "lunch" | "dinner";

export type Allergen =
  | "nuts"
  | "dairy"
  | "eggs"
  | "shellfish"
  | "soy"
  | "gluten"
  | "sesame"
  | "fish";

export type MealTag = "vegetarian" | "vegan" | "gluten-free" | "keto";

export type Cuisine =
  | "Italian"
  | "Indian"
  | "Spanish"
  | "American"
  | "Mexican"
  | "Mediterranean"
  | "Asian"
  | "Japanese"
  | "Thai"
  | "Middle Eastern"
  | "British"
  | "French"
  | "Korean";

export interface Meal {
  id: string;
  name: string;
  type: MealType;
  calories: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
  tags: MealTag[];
  allergens: Allergen[];
  cuisines: Cuisine[];
  steps: string[];
  description: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// BREAKFAST — 22 meals
// ─────────────────────────────────────────────────────────────────────────────
const BREAKFAST: Meal[] = [
  {
    id: "b1",
    name: "Avocado Toast with Poached Eggs",
    type: "breakfast",
    calories: 380,
    protein_g: 15,
    carbs_g: 32,
    fat_g: 22,
    tags: ["vegetarian"],
    allergens: ["eggs", "gluten"],
    cuisines: ["American", "Mediterranean"],
    description: "Creamy avocado on toasted sourdough topped with perfectly poached eggs.",
    steps: [
      "Toast 2 slices of sourdough bread.",
      "Mash 1 avocado with lemon juice, salt and pepper.",
      "Bring a pan of water to a gentle simmer, add a splash of vinegar.",
      "Crack eggs into the water and poach for 3–4 minutes.",
      "Spread avocado on toast, top with eggs, chilli flakes and sea salt.",
    ],
  },
  {
    id: "b2",
    name: "Greek Yogurt Parfait",
    type: "breakfast",
    calories: 320,
    protein_g: 18,
    carbs_g: 42,
    fat_g: 7,
    tags: ["vegetarian", "gluten-free"],
    allergens: ["dairy"],
    cuisines: ["Mediterranean", "American"],
    description: "Layered yogurt, granola and fresh berries for a balanced breakfast.",
    steps: [
      "Spoon 200g Greek yogurt into a tall glass.",
      "Add a layer of granola (skip for gluten-free version).",
      "Add a layer of mixed fresh berries.",
      "Drizzle with honey and repeat layers if desired.",
    ],
  },
  {
    id: "b3",
    name: "Banana Oat Pancakes",
    type: "breakfast",
    calories: 410,
    protein_g: 14,
    carbs_g: 58,
    fat_g: 12,
    tags: ["vegetarian"],
    allergens: ["eggs", "gluten", "dairy"],
    cuisines: ["American"],
    description: "Fluffy pancakes made with ripe banana and oats — naturally sweet.",
    steps: [
      "Blend 1 ripe banana, 1 cup rolled oats, 2 eggs and 50ml milk until smooth.",
      "Heat a non-stick pan over medium heat, lightly grease with butter.",
      "Pour small rounds of batter, cook 2–3 minutes per side until golden.",
      "Serve with maple syrup and fresh fruit.",
    ],
  },
  {
    id: "b4",
    name: "Tropical Smoothie Bowl",
    type: "breakfast",
    calories: 280,
    protein_g: 6,
    carbs_g: 52,
    fat_g: 7,
    tags: ["vegan", "gluten-free"],
    allergens: [],
    cuisines: ["American", "Asian"],
    description: "Thick mango-pineapple smoothie base topped with seeds and coconut.",
    steps: [
      "Blend 150g frozen mango, 100g frozen pineapple and 100ml coconut milk until thick.",
      "Pour into a bowl.",
      "Top with sliced banana, chia seeds, shredded coconut and granola.",
    ],
  },
  {
    id: "b5",
    name: "Shakshuka",
    type: "breakfast",
    calories: 340,
    protein_g: 18,
    carbs_g: 22,
    fat_g: 17,
    tags: ["vegetarian", "gluten-free"],
    allergens: ["eggs"],
    cuisines: ["Middle Eastern", "Mediterranean"],
    description: "Eggs poached in a spiced tomato and pepper sauce — a Middle Eastern classic.",
    steps: [
      "Sauté 1 diced onion and 2 garlic cloves in olive oil until soft.",
      "Add 1 diced red pepper and cook 3 minutes.",
      "Pour in 400g chopped tomatoes, 1 tsp cumin, paprika and chilli flakes; simmer 10 minutes.",
      "Make 4 wells in the sauce and crack in the eggs.",
      "Cover and cook 5–7 minutes until whites are set.",
      "Serve with crusty bread or pita.",
    ],
  },
  {
    id: "b6",
    name: "Overnight Oats",
    type: "breakfast",
    calories: 360,
    protein_g: 13,
    carbs_g: 55,
    fat_g: 9,
    tags: ["vegetarian"],
    allergens: ["gluten", "dairy"],
    cuisines: ["American", "British"],
    description: "Prep-ahead oats soaked overnight with milk and toppings of your choice.",
    steps: [
      "Combine 80g rolled oats, 200ml milk and 1 tbsp chia seeds in a jar.",
      "Stir well, cover and refrigerate overnight (at least 6 hours).",
      "In the morning, top with berries, nuts or honey.",
    ],
  },
  {
    id: "b7",
    name: "Masala Omelette",
    type: "breakfast",
    calories: 290,
    protein_g: 20,
    carbs_g: 8,
    fat_g: 19,
    tags: ["vegetarian", "gluten-free", "keto"],
    allergens: ["eggs", "dairy"],
    cuisines: ["Indian"],
    description: "Spiced Indian-style omelette with onion, tomato and green chilli.",
    steps: [
      "Beat 3 eggs with salt, turmeric and a pinch of red chilli powder.",
      "Fold in finely diced onion, tomato and green chilli.",
      "Heat oil in a pan, pour in egg mixture and cook on medium heat.",
      "Fold over once edges are set; cook another 1–2 minutes.",
      "Serve with toast or roti.",
    ],
  },
  {
    id: "b8",
    name: "French Toast",
    type: "breakfast",
    calories: 420,
    protein_g: 14,
    carbs_g: 52,
    fat_g: 15,
    tags: ["vegetarian"],
    allergens: ["eggs", "gluten", "dairy"],
    cuisines: ["French", "American"],
    description: "Classic golden-brown French toast dusted with cinnamon sugar.",
    steps: [
      "Whisk 2 eggs with 80ml milk, 1 tsp vanilla and 1 tsp cinnamon.",
      "Dip thick bread slices in the egg mixture on both sides.",
      "Cook in buttered pan over medium heat, 2–3 minutes each side until golden.",
      "Serve with maple syrup and powdered sugar.",
    ],
  },
  {
    id: "b9",
    name: "Chia Seed Pudding",
    type: "breakfast",
    calories: 240,
    protein_g: 8,
    carbs_g: 28,
    fat_g: 11,
    tags: ["vegan", "gluten-free"],
    allergens: [],
    cuisines: ["American"],
    description: "Creamy coconut chia pudding with mango and lime zest.",
    steps: [
      "Mix 4 tbsp chia seeds with 300ml coconut milk and 1 tsp maple syrup.",
      "Stir well, refrigerate for at least 4 hours or overnight.",
      "Stir again before serving to break up any clumps.",
      "Top with diced mango and lime zest.",
    ],
  },
  {
    id: "b10",
    name: "Keto Bacon & Eggs",
    type: "breakfast",
    calories: 450,
    protein_g: 32,
    carbs_g: 2,
    fat_g: 36,
    tags: ["gluten-free", "keto"],
    allergens: ["eggs"],
    cuisines: ["American", "British"],
    description: "High-protein, zero-carb bacon and eggs to start the day right.",
    steps: [
      "Cook 4 rashers of bacon in a dry pan until crispy; set aside.",
      "Crack 3 eggs into the same pan with rendered bacon fat.",
      "Cook sunny-side up or over-easy to your preference.",
      "Season with salt and black pepper. Serve with sliced avocado.",
    ],
  },
  {
    id: "b11",
    name: "Italian Frittata",
    type: "breakfast",
    calories: 310,
    protein_g: 22,
    carbs_g: 8,
    fat_g: 21,
    tags: ["vegetarian", "gluten-free", "keto"],
    allergens: ["eggs", "dairy"],
    cuisines: ["Italian"],
    description: "Baked Italian egg dish loaded with roasted vegetables and Parmesan.",
    steps: [
      "Preheat oven to 200°C.",
      "Sauté diced courgette, peppers and cherry tomatoes in an oven-safe pan.",
      "Whisk 6 eggs with 50ml cream, salt, pepper and grated Parmesan.",
      "Pour egg mix over vegetables; cook 3 minutes on hob until edges set.",
      "Transfer to oven and bake 12 minutes until puffed and golden.",
    ],
  },
  {
    id: "b12",
    name: "Japanese Tamago Gohan",
    type: "breakfast",
    calories: 330,
    protein_g: 14,
    carbs_g: 48,
    fat_g: 8,
    tags: ["gluten-free"],
    allergens: ["eggs", "soy"],
    cuisines: ["Japanese"],
    description: "Simple Japanese rice bowl with a raw egg stirred in and finished with soy.",
    steps: [
      "Cook 200g Japanese short-grain rice and scoop into a bowl while hot.",
      "Make a small well in the centre; crack a fresh egg into it.",
      "Drizzle 1 tsp soy sauce and a tiny splash of sesame oil.",
      "Stir vigorously until the egg is emulsified into the hot rice.",
      "Top with spring onion and nori strips.",
    ],
  },
  {
    id: "b13",
    name: "Spanish Tortilla de Patatas",
    type: "breakfast",
    calories: 390,
    protein_g: 16,
    carbs_g: 38,
    fat_g: 18,
    tags: ["vegetarian", "gluten-free"],
    allergens: ["eggs"],
    cuisines: ["Spanish"],
    description: "Classic Spanish potato omelette — hearty, filling and served at room temperature.",
    steps: [
      "Thinly slice 2 medium potatoes and 1 onion.",
      "Cook slowly in generous olive oil over low heat for 20 minutes until soft.",
      "Beat 4 eggs, season, then add the drained potato mix.",
      "Return to the pan, cook covered on low until mostly set (8 minutes).",
      "Flip onto a plate then slide back in; cook another 5 minutes.",
    ],
  },
  {
    id: "b14",
    name: "Blueberry Waffles",
    type: "breakfast",
    calories: 460,
    protein_g: 12,
    carbs_g: 66,
    fat_g: 16,
    tags: ["vegetarian"],
    allergens: ["eggs", "gluten", "dairy"],
    cuisines: ["American"],
    description: "Light and crispy waffles bursting with fresh blueberries.",
    steps: [
      "Mix 200g flour, 1 tsp baking powder and a pinch of salt.",
      "Whisk 2 eggs with 250ml milk, 50g melted butter and 1 tsp vanilla.",
      "Combine wet and dry ingredients; fold in 100g blueberries.",
      "Cook in a preheated waffle iron until golden and crisp.",
      "Serve with maple syrup and extra blueberries.",
    ],
  },
  {
    id: "b15",
    name: "Protein Oatmeal Bowl",
    type: "breakfast",
    calories: 380,
    protein_g: 28,
    carbs_g: 44,
    fat_g: 9,
    tags: ["vegetarian"],
    allergens: ["gluten", "dairy"],
    cuisines: ["American", "British"],
    description: "Hearty oats cooked with protein powder and topped with nut butter.",
    steps: [
      "Cook 80g rolled oats in 300ml milk over medium heat, stirring often.",
      "Remove from heat; stir in one scoop of unflavoured or vanilla protein powder.",
      "Transfer to a bowl; top with 1 tbsp almond butter and banana slices.",
      "Drizzle with honey and add a sprinkle of cinnamon.",
    ],
  },
  {
    id: "b16",
    name: "Coconut Chia Pudding",
    type: "breakfast",
    calories: 220,
    protein_g: 5,
    carbs_g: 24,
    fat_g: 12,
    tags: ["vegan", "gluten-free"],
    allergens: [],
    cuisines: ["Asian", "American"],
    description: "Light vegan pudding made with coconut milk and topped with tropical fruit.",
    steps: [
      "Mix 3 tbsp chia seeds into 250ml full-fat coconut milk.",
      "Sweeten with 1 tbsp maple syrup and stir thoroughly.",
      "Refrigerate overnight or at least 4 hours.",
      "Top with kiwi, passion fruit and toasted coconut flakes.",
    ],
  },
  {
    id: "b17",
    name: "Egg & Veggie Breakfast Burrito",
    type: "breakfast",
    calories: 430,
    protein_g: 22,
    carbs_g: 44,
    fat_g: 17,
    tags: ["vegetarian"],
    allergens: ["eggs", "gluten", "dairy"],
    cuisines: ["Mexican", "American"],
    description: "Scrambled eggs, black beans and cheese wrapped in a warm flour tortilla.",
    steps: [
      "Scramble 3 eggs in butter with salt and pepper; set aside.",
      "Warm 100g canned black beans with cumin and smoked paprika.",
      "Heat a large flour tortilla on a dry pan.",
      "Fill with eggs, beans, grated cheese, avocado and salsa.",
      "Roll tightly and serve immediately.",
    ],
  },
  {
    id: "b18",
    name: "Bircher Muesli",
    type: "breakfast",
    calories: 350,
    protein_g: 11,
    carbs_g: 54,
    fat_g: 9,
    tags: ["vegetarian"],
    allergens: ["gluten", "dairy", "nuts"],
    cuisines: ["British", "Mediterranean"],
    description: "Swiss-style overnight muesli with apple, yogurt and toasted nuts.",
    steps: [
      "Soak 80g rolled oats in 150ml apple juice overnight.",
      "In the morning, stir in 100g yogurt and grated apple.",
      "Add lemon zest and a drizzle of honey.",
      "Top with toasted almonds, sunflower seeds and fresh berries.",
    ],
  },
  {
    id: "b19",
    name: "Acai Bowl",
    type: "breakfast",
    calories: 300,
    protein_g: 7,
    carbs_g: 50,
    fat_g: 9,
    tags: ["vegan", "gluten-free"],
    allergens: [],
    cuisines: ["American"],
    description: "Vibrant purple acai base topped with granola, fruit and coconut.",
    steps: [
      "Blend 100g frozen acai pulp, 50g frozen blueberries and 50ml almond milk.",
      "Keep the texture thick; add more frozen fruit if too thin.",
      "Pour into a bowl and top with granola, sliced banana, strawberries and coconut.",
    ],
  },
  {
    id: "b20",
    name: "Korean Egg Drop Soup",
    type: "breakfast",
    calories: 180,
    protein_g: 12,
    carbs_g: 10,
    fat_g: 8,
    tags: ["gluten-free"],
    allergens: ["eggs", "soy"],
    cuisines: ["Korean"],
    description: "Light and warming egg drop soup with spring onion and sesame oil.",
    steps: [
      "Bring 600ml vegetable stock to a simmer in a saucepan.",
      "Season with 1 tsp soy sauce, a pinch of white pepper and sesame oil.",
      "Whisk 2 eggs, then slowly drizzle into the simmering broth while stirring.",
      "Remove from heat immediately; top with sliced spring onion.",
    ],
  },
  {
    id: "b21",
    name: "Spinach & Feta Breakfast Wrap",
    type: "breakfast",
    calories: 370,
    protein_g: 18,
    carbs_g: 38,
    fat_g: 16,
    tags: ["vegetarian"],
    allergens: ["eggs", "gluten", "dairy"],
    cuisines: ["Mediterranean", "British"],
    description: "Scrambled eggs with wilted spinach and crumbled feta in a warm wrap.",
    steps: [
      "Wilt a handful of fresh spinach in a pan with a little olive oil.",
      "Beat 2 eggs and scramble into the pan with the spinach.",
      "Crumble in 30g feta and stir gently.",
      "Spoon into a warm tortilla wrap; fold and serve.",
    ],
  },
  {
    id: "b22",
    name: "Peanut Butter Banana Toast",
    type: "breakfast",
    calories: 400,
    protein_g: 14,
    carbs_g: 50,
    fat_g: 17,
    tags: ["vegan"],
    allergens: ["gluten", "nuts"],
    cuisines: ["American"],
    description: "Quick vegan toast loaded with peanut butter, banana and a honey drizzle.",
    steps: [
      "Toast 2 slices of whole-grain bread.",
      "Spread 2 tbsp peanut butter generously on each slice.",
      "Layer with thinly sliced banana.",
      "Drizzle with honey and sprinkle with cinnamon.",
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// LUNCH — 21 meals
// ─────────────────────────────────────────────────────────────────────────────
const LUNCH: Meal[] = [
  {
    id: "l1",
    name: "Chicken Caesar Salad",
    type: "lunch",
    calories: 480,
    protein_g: 38,
    carbs_g: 18,
    fat_g: 26,
    tags: ["gluten-free"],
    allergens: ["dairy", "eggs", "fish"],
    cuisines: ["American", "Italian"],
    description: "Grilled chicken on romaine with classic Caesar dressing and Parmesan.",
    steps: [
      "Season a chicken breast and grill 6 minutes each side; slice thinly.",
      "Toss chopped romaine lettuce with Caesar dressing.",
      "Arrange lettuce in a bowl, top with chicken slices and shaved Parmesan.",
      "Add croutons if not avoiding gluten and finish with black pepper.",
    ],
  },
  {
    id: "l2",
    name: "Red Lentil Soup",
    type: "lunch",
    calories: 320,
    protein_g: 17,
    carbs_g: 48,
    fat_g: 7,
    tags: ["vegan", "gluten-free"],
    allergens: [],
    cuisines: ["Middle Eastern", "Indian", "Mediterranean"],
    description: "Warming spiced red lentil soup with lemon and cumin.",
    steps: [
      "Sauté 1 diced onion and 3 garlic cloves in olive oil for 5 minutes.",
      "Add 1 tsp cumin, 1 tsp turmeric and 0.5 tsp cayenne; cook 1 minute.",
      "Add 200g red lentils and 1 litre vegetable stock; bring to a boil.",
      "Simmer 20 minutes until lentils are soft; blend partially.",
      "Finish with lemon juice and a drizzle of olive oil.",
    ],
  },
  {
    id: "l3",
    name: "Quinoa Buddha Bowl",
    type: "lunch",
    calories: 440,
    protein_g: 18,
    carbs_g: 56,
    fat_g: 15,
    tags: ["vegan", "gluten-free"],
    allergens: ["sesame"],
    cuisines: ["American", "Mediterranean"],
    description: "Nourishing bowl with quinoa, roasted chickpeas, greens and tahini dressing.",
    steps: [
      "Cook 150g quinoa according to packet; set aside.",
      "Toss drained chickpeas in olive oil, paprika and cumin; roast at 200°C for 25 minutes.",
      "Arrange quinoa in a bowl with cucumber, cherry tomatoes, avocado and roasted chickpeas.",
      "Drizzle with tahini thinned with lemon juice and water.",
    ],
  },
  {
    id: "l4",
    name: "BLT Sandwich",
    type: "lunch",
    calories: 480,
    protein_g: 22,
    carbs_g: 42,
    fat_g: 24,
    tags: [],
    allergens: ["gluten", "eggs"],
    cuisines: ["American", "British"],
    description: "Classic bacon, lettuce and tomato sandwich with mayo.",
    steps: [
      "Cook 4 rashers of back bacon until crispy.",
      "Toast 2 slices of white or wholegrain bread.",
      "Spread mayo on one side; layer with lettuce, sliced tomato and bacon.",
      "Season with salt and black pepper; sandwich together and cut diagonally.",
    ],
  },
  {
    id: "l5",
    name: "Chicken Tikka Wrap",
    type: "lunch",
    calories: 510,
    protein_g: 36,
    carbs_g: 46,
    fat_g: 16,
    tags: [],
    allergens: ["gluten", "dairy"],
    cuisines: ["Indian", "British"],
    description: "Tender tikka-spiced chicken with mint yogurt and salad in a flatbread.",
    steps: [
      "Marinate chicken in yogurt, tikka spice paste, lemon juice for 30 minutes.",
      "Grill or pan-fry chicken until charred and cooked through; slice.",
      "Warm a flatbread; spread with mint-yogurt sauce.",
      "Fill with chicken, shredded lettuce, diced tomato and red onion; roll tightly.",
    ],
  },
  {
    id: "l6",
    name: "Tuna Poke Bowl",
    type: "lunch",
    calories: 420,
    protein_g: 34,
    carbs_g: 44,
    fat_g: 10,
    tags: ["gluten-free"],
    allergens: ["soy", "fish", "sesame"],
    cuisines: ["Japanese", "American"],
    description: "Hawaiian-inspired bowl with sushi-grade tuna, edamame and soy marinade.",
    steps: [
      "Dice 200g sushi-grade tuna into 2cm cubes.",
      "Marinate in 2 tbsp soy sauce, 1 tsp sesame oil and sriracha for 10 minutes.",
      "Cook 150g sushi rice and spread in a bowl.",
      "Top with marinated tuna, edamame, cucumber, avocado and pickled ginger.",
      "Finish with sesame seeds and spring onion.",
    ],
  },
  {
    id: "l7",
    name: "Falafel Pitta",
    type: "lunch",
    calories: 460,
    protein_g: 18,
    carbs_g: 62,
    fat_g: 14,
    tags: ["vegan"],
    allergens: ["gluten", "sesame"],
    cuisines: ["Middle Eastern"],
    description: "Crispy homemade falafel in pitta with hummus and tabbouleh.",
    steps: [
      "Blend canned chickpeas with garlic, cumin, coriander, parsley and a little flour.",
      "Shape into small patties and shallow-fry in oil for 3 minutes each side.",
      "Warm pitta bread; spread with hummus.",
      "Fill with falafel, shredded lettuce, tomato, onion and drizzle tahini.",
    ],
  },
  {
    id: "l8",
    name: "Thai Peanut Noodles",
    type: "lunch",
    calories: 490,
    protein_g: 16,
    carbs_g: 62,
    fat_g: 19,
    tags: ["vegan"],
    allergens: ["gluten", "nuts", "soy"],
    cuisines: ["Thai", "Asian"],
    description: "Cold rice noodles tossed in a spicy peanut-lime sauce with crunchy veg.",
    steps: [
      "Cook rice noodles according to packet; rinse under cold water.",
      "Whisk together 3 tbsp peanut butter, 2 tbsp soy sauce, lime juice, garlic and chilli.",
      "Toss noodles in the dressing with shredded carrot, cucumber and red cabbage.",
      "Top with crushed peanuts, fresh coriander and lime wedges.",
    ],
  },
  {
    id: "l9",
    name: "Greek Salad with Chicken",
    type: "lunch",
    calories: 400,
    protein_g: 36,
    carbs_g: 14,
    fat_g: 20,
    tags: ["gluten-free"],
    allergens: ["dairy"],
    cuisines: ["Mediterranean"],
    description: "Grilled chicken over a classic Greek salad with Kalamata olives and feta.",
    steps: [
      "Season chicken breast and grill or pan-fry until cooked through; slice.",
      "Chop tomatoes, cucumber and red onion into chunks.",
      "Toss with Kalamata olives, crumbled feta and dried oregano.",
      "Dress with olive oil and red wine vinegar; top with sliced chicken.",
    ],
  },
  {
    id: "l10",
    name: "Mexican Chicken Burrito Bowl",
    type: "lunch",
    calories: 530,
    protein_g: 40,
    carbs_g: 54,
    fat_g: 14,
    tags: ["gluten-free"],
    allergens: ["dairy"],
    cuisines: ["Mexican"],
    description: "All the burrito flavours without the wrap — rice, chicken, beans and guac.",
    steps: [
      "Cook 150g long-grain rice with chicken stock and cumin.",
      "Season chicken with smoked paprika, cumin and garlic; pan-fry until golden.",
      "Warm black beans with a little chipotle paste.",
      "Build a bowl: rice, chicken, beans, corn, salsa, sour cream and guacamole.",
    ],
  },
  {
    id: "l11",
    name: "Italian Caprese",
    type: "lunch",
    calories: 340,
    protein_g: 18,
    carbs_g: 12,
    fat_g: 22,
    tags: ["vegetarian", "gluten-free", "keto"],
    allergens: ["dairy"],
    cuisines: ["Italian"],
    description: "Simple Italian classic of buffalo mozzarella, heirloom tomatoes and basil.",
    steps: [
      "Slice 200g buffalo mozzarella and 3 large heirloom tomatoes.",
      "Alternate slices on a plate.",
      "Tuck fresh basil leaves between each slice.",
      "Drizzle with good extra-virgin olive oil and a splash of balsamic glaze.",
      "Season with sea salt and black pepper.",
    ],
  },
  {
    id: "l12",
    name: "Miso Tofu Soup",
    type: "lunch",
    calories: 220,
    protein_g: 14,
    carbs_g: 18,
    fat_g: 9,
    tags: ["vegan"],
    allergens: ["soy", "gluten"],
    cuisines: ["Japanese"],
    description: "Warming Japanese miso soup with silken tofu, wakame and spring onion.",
    steps: [
      "Heat 800ml water and stir in 3 tbsp white miso paste (do not boil).",
      "Add cubed silken tofu and rehydrated wakame seaweed.",
      "Heat gently for 3 minutes.",
      "Serve in bowls topped with thinly sliced spring onion.",
    ],
  },
  {
    id: "l13",
    name: "Spanish Gazpacho",
    type: "lunch",
    calories: 180,
    protein_g: 4,
    carbs_g: 22,
    fat_g: 8,
    tags: ["vegan", "gluten-free"],
    allergens: [],
    cuisines: ["Spanish"],
    description: "Chilled blended Spanish tomato soup served with a drizzle of olive oil.",
    steps: [
      "Roughly chop 800g ripe tomatoes, 1 cucumber, 2 peppers and 2 garlic cloves.",
      "Blend all vegetables with 100ml olive oil, 2 tbsp sherry vinegar and salt.",
      "Strain for a smoother consistency if desired.",
      "Chill for at least 1 hour before serving with ice.",
    ],
  },
  {
    id: "l14",
    name: "BBQ Chicken Sandwich",
    type: "lunch",
    calories: 560,
    protein_g: 38,
    carbs_g: 52,
    fat_g: 18,
    tags: [],
    allergens: ["gluten", "dairy"],
    cuisines: ["American"],
    description: "Pulled BBQ chicken piled high in a toasted brioche bun with coleslaw.",
    steps: [
      "Slow-cook chicken thighs in BBQ sauce for 2 hours on low; shred.",
      "Mix shredded cabbage and carrot with a creamy coleslaw dressing.",
      "Toast brioche buns; pile with BBQ chicken and coleslaw.",
      "Top with pickles and extra BBQ sauce.",
    ],
  },
  {
    id: "l15",
    name: "Mediterranean Hummus Plate",
    type: "lunch",
    calories: 380,
    protein_g: 14,
    carbs_g: 46,
    fat_g: 16,
    tags: ["vegan"],
    allergens: ["sesame", "gluten"],
    cuisines: ["Mediterranean", "Middle Eastern"],
    description: "Creamy hummus served with warm pita, olives, cucumbers and cherry tomatoes.",
    steps: [
      "Blend 400g canned chickpeas with 3 tbsp tahini, garlic, lemon juice and olive oil.",
      "Season with cumin and salt; thin with cold water to desired consistency.",
      "Spread on a large plate and make a well in the centre; drizzle olive oil.",
      "Arrange pita bread, olives, cucumber, carrot sticks and tomatoes around the hummus.",
    ],
  },
  {
    id: "l16",
    name: "Egg Fried Rice",
    type: "lunch",
    calories: 440,
    protein_g: 16,
    carbs_g: 60,
    fat_g: 14,
    tags: ["vegetarian"],
    allergens: ["eggs", "soy"],
    cuisines: ["Asian", "Japanese", "Korean"],
    description: "Quick classic fried rice with scrambled egg, peas and soy sauce.",
    steps: [
      "Use cold day-old cooked rice for best results.",
      "Heat a wok until very hot; add oil and scramble 2 beaten eggs quickly.",
      "Add the rice and stir-fry on high heat for 3 minutes.",
      "Add frozen peas, soy sauce, sesame oil and white pepper.",
      "Toss for another 2 minutes and garnish with spring onion.",
    ],
  },
  {
    id: "l17",
    name: "Vietnamese Spring Rolls",
    type: "lunch",
    calories: 280,
    protein_g: 14,
    carbs_g: 36,
    fat_g: 7,
    tags: ["gluten-free"],
    allergens: ["soy", "shellfish"],
    cuisines: ["Asian"],
    description: "Fresh rice-paper rolls with prawn, vermicelli, herbs and peanut dip.",
    steps: [
      "Cook rice vermicelli and cool under cold water.",
      "Cook prawns in salted water 2–3 minutes; cool and halve.",
      "Soften rice paper sheets in warm water, one at a time.",
      "Layer prawns, noodles, shredded carrot, cucumber and mint on rice paper.",
      "Roll tightly. Serve with peanut or hoisin dipping sauce.",
    ],
  },
  {
    id: "l18",
    name: "Tomato Basil Soup",
    type: "lunch",
    calories: 210,
    protein_g: 5,
    carbs_g: 28,
    fat_g: 9,
    tags: ["vegan", "gluten-free"],
    allergens: [],
    cuisines: ["Italian", "American", "British"],
    description: "Velvety roasted tomato and basil soup with a swirl of olive oil.",
    steps: [
      "Halve 1kg tomatoes and roast at 200°C with garlic and olive oil for 30 minutes.",
      "Blend with 500ml vegetable stock until smooth.",
      "Simmer in a pan for 10 minutes; season generously with salt and pepper.",
      "Stir in a handful of fresh basil and blend again.",
      "Serve with crusty bread and a drizzle of good olive oil.",
    ],
  },
  {
    id: "l19",
    name: "Chickpea Spinach Stew",
    type: "lunch",
    calories: 360,
    protein_g: 16,
    carbs_g: 48,
    fat_g: 10,
    tags: ["vegan", "gluten-free"],
    allergens: [],
    cuisines: ["Mediterranean", "Middle Eastern"],
    description: "Hearty spiced chickpea and spinach stew perfect for meal prep.",
    steps: [
      "Sauté 1 diced onion, 4 garlic cloves and 1 tsp ginger in oil.",
      "Add 1 tsp each cumin, coriander and paprika; cook 1 minute.",
      "Add 400g canned chickpeas and 400g chopped tomatoes; simmer 15 minutes.",
      "Stir in 200g baby spinach until wilted.",
      "Season and serve over rice or with flatbread.",
    ],
  },
  {
    id: "l20",
    name: "Smoked Salmon Bagel",
    type: "lunch",
    calories: 430,
    protein_g: 26,
    carbs_g: 46,
    fat_g: 14,
    tags: [],
    allergens: ["gluten", "dairy", "fish", "eggs"],
    cuisines: ["American", "British"],
    description: "New York-style bagel with cream cheese, smoked salmon and capers.",
    steps: [
      "Slice and toast a plain or sesame bagel.",
      "Spread generously with cream cheese.",
      "Layer with smoked salmon, thinly sliced red onion and capers.",
      "Add sliced tomato and cucumber.",
      "Finish with black pepper and a squeeze of lemon juice.",
    ],
  },
  {
    id: "l21",
    name: "Korean Bibimbap",
    type: "lunch",
    calories: 490,
    protein_g: 22,
    carbs_g: 68,
    fat_g: 13,
    tags: ["gluten-free"],
    allergens: ["eggs", "soy", "sesame"],
    cuisines: ["Korean"],
    description: "Korean rice bowl with sautéed vegetables, egg and gochujang sauce.",
    steps: [
      "Cook 180g short-grain rice; spread in a hot stone bowl or regular bowl.",
      "Sauté spinach, bean sprouts and carrots separately with soy and sesame oil.",
      "Arrange vegetables over the rice.",
      "Fry an egg sunny-side up; place on top.",
      "Add a spoonful of gochujang sauce and mix everything together to serve.",
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// DINNER — 21 meals
// ─────────────────────────────────────────────────────────────────────────────
const DINNER: Meal[] = [
  {
    id: "d1",
    name: "Chicken Tikka Masala",
    type: "dinner",
    calories: 520,
    protein_g: 38,
    carbs_g: 22,
    fat_g: 28,
    tags: ["gluten-free"],
    allergens: ["dairy"],
    cuisines: ["Indian", "British"],
    description: "Succulent chicken in a rich, aromatic tomato-cream sauce.",
    steps: [
      "Marinate chicken chunks in yogurt, garlic, ginger and tikka spice for 30 min.",
      "Grill or pan-fry chicken until charred; set aside.",
      "Sauté onion, garlic and ginger; add crushed tomatoes, cumin and garam masala.",
      "Simmer 15 minutes; stir in cream and the cooked chicken.",
      "Simmer another 5 minutes; garnish with fresh coriander.",
      "Serve with basmati rice or naan.",
    ],
  },
  {
    id: "d2",
    name: "Spaghetti Bolognese",
    type: "dinner",
    calories: 580,
    protein_g: 34,
    carbs_g: 62,
    fat_g: 18,
    tags: [],
    allergens: ["gluten", "dairy"],
    cuisines: ["Italian"],
    description: "Classic slow-cooked beef ragù tossed with spaghetti and Parmesan.",
    steps: [
      "Sauté finely diced onion, celery and carrot in olive oil for 10 minutes.",
      "Add 500g minced beef; brown well, breaking up lumps.",
      "Pour in 200ml red wine; reduce by half.",
      "Add 400g crushed tomatoes, 1 tbsp tomato purée and seasoning.",
      "Simmer covered for 45 minutes, stirring occasionally.",
      "Toss with cooked spaghetti; finish with grated Parmesan.",
    ],
  },
  {
    id: "d3",
    name: "Grilled Salmon with Asparagus",
    type: "dinner",
    calories: 460,
    protein_g: 40,
    carbs_g: 8,
    fat_g: 28,
    tags: ["gluten-free", "keto"],
    allergens: ["fish"],
    cuisines: ["American", "Mediterranean"],
    description: "Pan-seared salmon with lemon butter and tender grilled asparagus.",
    steps: [
      "Season salmon fillets with salt, pepper and smoked paprika.",
      "Heat a pan over high heat; cook salmon skin-side down for 4 minutes.",
      "Flip and cook another 3 minutes; set aside.",
      "Grill asparagus spears with olive oil and salt for 5 minutes.",
      "Melt butter with lemon zest and capers; pour over salmon to serve.",
    ],
  },
  {
    id: "d4",
    name: "Black Bean Tacos",
    type: "dinner",
    calories: 420,
    protein_g: 16,
    carbs_g: 56,
    fat_g: 14,
    tags: ["vegan", "gluten-free"],
    allergens: [],
    cuisines: ["Mexican"],
    description: "Smoky black bean tacos with mango salsa and chipotle crema.",
    steps: [
      "Heat black beans with cumin, smoked paprika and a little chipotle sauce.",
      "Dice mango, red onion and coriander for the salsa; add lime juice.",
      "Warm corn tortillas on a dry pan.",
      "Fill each tortilla with beans, mango salsa and sliced avocado.",
      "Add a drizzle of vegan chipotle sauce and extra lime.",
    ],
  },
  {
    id: "d5",
    name: "Butter Chicken",
    type: "dinner",
    calories: 540,
    protein_g: 36,
    carbs_g: 24,
    fat_g: 30,
    tags: ["gluten-free"],
    allergens: ["dairy"],
    cuisines: ["Indian"],
    description: "Mild and creamy tomato-butter sauce with tender chicken pieces.",
    steps: [
      "Marinate chicken in yogurt, cumin and coriander for 1 hour; grill until charred.",
      "Blend onion, cashews, tomatoes and spices into a smooth sauce.",
      "Cook sauce in butter for 5 minutes; add cream and adjust seasoning.",
      "Add grilled chicken and simmer 10 minutes.",
      "Garnish with cream and fenugreek leaves; serve with rice.",
    ],
  },
  {
    id: "d6",
    name: "Beef & Vegetable Stir Fry",
    type: "dinner",
    calories: 480,
    protein_g: 34,
    carbs_g: 32,
    fat_g: 20,
    tags: ["gluten-free"],
    allergens: ["soy"],
    cuisines: ["Asian", "Korean"],
    description: "Tender beef strips with crunchy vegetables in an oyster-soy sauce.",
    steps: [
      "Slice beef steak thinly against the grain; marinate in soy, garlic and ginger.",
      "Stir-fry beef in a hot wok for 2 minutes; remove.",
      "Stir-fry broccoli, peppers and snap peas for 3 minutes.",
      "Return beef, add oyster sauce and a little sesame oil.",
      "Toss together and serve over steamed rice.",
    ],
  },
  {
    id: "d7",
    name: "Shrimp Linguine",
    type: "dinner",
    calories: 520,
    protein_g: 30,
    carbs_g: 54,
    fat_g: 18,
    tags: [],
    allergens: ["shellfish", "gluten", "dairy"],
    cuisines: ["Italian", "American"],
    description: "Garlic butter shrimp tossed through linguine with a splash of white wine.",
    steps: [
      "Cook linguine in salted boiling water until al dente; reserve pasta water.",
      "Sauté minced garlic in butter; add shrimp and cook 2 minutes each side.",
      "Deglaze with 100ml white wine; reduce by half.",
      "Toss in linguine with a splash of pasta water and fresh parsley.",
      "Finish with lemon juice and chilli flakes.",
    ],
  },
  {
    id: "d8",
    name: "Thai Green Vegetable Curry",
    type: "dinner",
    calories: 440,
    protein_g: 12,
    carbs_g: 38,
    fat_g: 26,
    tags: ["vegan", "gluten-free"],
    allergens: [],
    cuisines: ["Thai"],
    description: "Fragrant coconut milk curry with green curry paste and seasonal vegetables.",
    steps: [
      "Fry 2 tbsp green curry paste in a pan with a spoon of coconut cream for 2 minutes.",
      "Pour in 400ml coconut milk and 200ml vegetable stock.",
      "Add broccoli, courgette, baby corn and mangetout.",
      "Simmer 10 minutes; add baby spinach and Thai basil.",
      "Serve with jasmine rice and lime wedges.",
    ],
  },
  {
    id: "d9",
    name: "Classic Cheeseburger",
    type: "dinner",
    calories: 660,
    protein_g: 40,
    carbs_g: 44,
    fat_g: 32,
    tags: [],
    allergens: ["gluten", "dairy", "eggs"],
    cuisines: ["American"],
    description: "Juicy beef patty with American cheese, lettuce, tomato and secret sauce.",
    steps: [
      "Mix 500g beef mince with Worcestershire sauce, salt and pepper; form into patties.",
      "Grill or pan-fry over high heat 3–4 minutes per side.",
      "Add cheese slice in last minute and cover with lid to melt.",
      "Toast brioche buns; spread with mayo and ketchup.",
      "Layer with lettuce, tomato, onion and the burger.",
    ],
  },
  {
    id: "d10",
    name: "Spanish Seafood Paella",
    type: "dinner",
    calories: 540,
    protein_g: 34,
    carbs_g: 64,
    fat_g: 12,
    tags: ["gluten-free"],
    allergens: ["shellfish", "fish"],
    cuisines: ["Spanish"],
    description: "Saffron-scented Spanish rice with mussels, prawns and squid.",
    steps: [
      "Fry chorizo and diced onion in olive oil; add paella rice and stir to coat.",
      "Add crushed tomatoes, saffron, smoked paprika and 800ml warm stock.",
      "Simmer uncovered 15 minutes without stirring.",
      "Arrange prawns, mussels and squid on top; cook another 8 minutes.",
      "Rest covered with foil for 5 minutes before serving with lemon.",
    ],
  },
  {
    id: "d11",
    name: "Japanese Teriyaki Chicken",
    type: "dinner",
    calories: 480,
    protein_g: 38,
    carbs_g: 42,
    fat_g: 14,
    tags: ["gluten-free"],
    allergens: ["soy", "gluten"],
    cuisines: ["Japanese"],
    description: "Glazed chicken thighs in a sweet soy teriyaki sauce with steamed rice.",
    steps: [
      "Mix 4 tbsp soy sauce, 2 tbsp mirin, 2 tbsp sake and 1 tbsp sugar.",
      "Score chicken thighs and cook skin-side down in an oiled pan for 8 minutes.",
      "Flip, pour in teriyaki sauce and cook another 8 minutes, basting frequently.",
      "Slice and serve over rice with steamed broccoli and sesame seeds.",
    ],
  },
  {
    id: "d12",
    name: "Italian Chicken Piccata",
    type: "dinner",
    calories: 430,
    protein_g: 36,
    carbs_g: 18,
    fat_g: 22,
    tags: [],
    allergens: ["gluten", "eggs", "dairy"],
    cuisines: ["Italian"],
    description: "Pan-fried chicken in a lemon-caper butter sauce with pasta.",
    steps: [
      "Flatten chicken breasts; dredge in seasoned flour and beaten egg.",
      "Fry in olive oil 4 minutes each side until golden.",
      "Deglaze the pan with white wine and lemon juice.",
      "Add capers and finish with cold butter to make a glossy sauce.",
      "Pour sauce over chicken; serve with linguine or mashed potato.",
    ],
  },
  {
    id: "d13",
    name: "Mexican Chicken Enchiladas",
    type: "dinner",
    calories: 560,
    protein_g: 36,
    carbs_g: 52,
    fat_g: 22,
    tags: [],
    allergens: ["gluten", "dairy"],
    cuisines: ["Mexican"],
    description: "Rolled chicken-and-cheese enchiladas baked in a smoky red sauce.",
    steps: [
      "Shred cooked chicken and mix with black beans and half the cheese.",
      "Warm tortillas; fill each with chicken mix and roll up.",
      "Place seam-side down in a baking dish.",
      "Pour enchilada sauce over, top with remaining cheese.",
      "Bake at 190°C for 25 minutes until bubbling; top with sour cream and coriander.",
    ],
  },
  {
    id: "d14",
    name: "Indian Dal Tadka",
    type: "dinner",
    calories: 380,
    protein_g: 18,
    carbs_g: 52,
    fat_g: 10,
    tags: ["vegan", "gluten-free"],
    allergens: [],
    cuisines: ["Indian"],
    description: "Comforting yellow lentil dal with a tempered spice oil poured on top.",
    steps: [
      "Rinse 200g yellow lentils; boil in water with turmeric and salt for 20 minutes.",
      "In a small pan heat ghee or oil; fry cumin seeds, garlic and dried red chilli.",
      "Add diced tomatoes and cook until pulpy.",
      "Pour the tadka over the cooked lentils; stir and simmer 5 minutes.",
      "Garnish with coriander; serve with rice or roti.",
    ],
  },
  {
    id: "d15",
    name: "American BBQ Ribs",
    type: "dinner",
    calories: 620,
    protein_g: 44,
    carbs_g: 28,
    fat_g: 36,
    tags: ["gluten-free"],
    allergens: [],
    cuisines: ["American"],
    description: "Fall-off-the-bone pork ribs slow-baked then finished on the grill.",
    steps: [
      "Rub ribs with brown sugar, smoked paprika, garlic powder, salt and pepper.",
      "Wrap tightly in foil and bake at 150°C for 2.5 hours.",
      "Unwrap; brush generously with BBQ sauce.",
      "Grill on high heat 5 minutes each side until caramelised.",
      "Rest 5 minutes; serve with coleslaw and corn.",
    ],
  },
  {
    id: "d16",
    name: "Mediterranean Stuffed Peppers",
    type: "dinner",
    calories: 420,
    protein_g: 18,
    carbs_g: 46,
    fat_g: 16,
    tags: ["vegetarian", "gluten-free"],
    allergens: ["dairy"],
    cuisines: ["Mediterranean"],
    description: "Bell peppers stuffed with herbed quinoa, feta and roasted vegetables.",
    steps: [
      "Cook 150g quinoa; stir in diced tomatoes, olives, herbs and crumbled feta.",
      "Halve and deseed 4 large peppers; place on a baking tray.",
      "Fill generously with the quinoa mixture.",
      "Drizzle with olive oil; bake at 200°C for 30 minutes until tender.",
      "Serve warm with a green salad.",
    ],
  },
  {
    id: "d17",
    name: "Moroccan Lamb Tagine",
    type: "dinner",
    calories: 560,
    protein_g: 40,
    carbs_g: 36,
    fat_g: 26,
    tags: ["gluten-free"],
    allergens: [],
    cuisines: ["Middle Eastern", "Mediterranean"],
    description: "Slow-cooked lamb with preserved lemon, apricots and warming spices.",
    steps: [
      "Brown lamb pieces in batches in a tagine or heavy casserole.",
      "Add onion, garlic, ginger, cumin, coriander, cinnamon and turmeric.",
      "Pour in 400ml stock, add preserved lemon and apricots.",
      "Cover and slow-cook at 160°C for 2 hours until lamb is tender.",
      "Scatter with toasted almonds and fresh mint; serve with couscous.",
    ],
  },
  {
    id: "d18",
    name: "Pesto Pasta with Roasted Tomatoes",
    type: "dinner",
    calories: 510,
    protein_g: 16,
    carbs_g: 62,
    fat_g: 22,
    tags: ["vegetarian"],
    allergens: ["gluten", "dairy", "nuts"],
    cuisines: ["Italian"],
    description: "Tossed with vibrant homemade basil pesto and sweet roasted cherry tomatoes.",
    steps: [
      "Blend 50g fresh basil, 30g pine nuts, 40g Parmesan, garlic and olive oil into pesto.",
      "Halve 250g cherry tomatoes; roast with oil at 200°C for 20 minutes.",
      "Cook 300g pasta until al dente; reserve 100ml pasta water.",
      "Toss hot pasta with pesto, roasted tomatoes and a splash of pasta water.",
      "Top with extra Parmesan and pine nuts.",
    ],
  },
  {
    id: "d19",
    name: "Korean Bibimbap",
    type: "dinner",
    calories: 540,
    protein_g: 26,
    carbs_g: 70,
    fat_g: 14,
    tags: ["gluten-free"],
    allergens: ["eggs", "soy", "sesame"],
    cuisines: ["Korean"],
    description: "Korean mixed rice bowl with seasoned vegetables, beef and gochujang.",
    steps: [
      "Cook rice and keep warm.",
      "Sauté marinated beef strips, spinach, bean sprouts and carrots separately with soy/sesame.",
      "Fry an egg sunny-side up.",
      "Arrange vegetables and beef over rice in sections.",
      "Place egg on top; add gochujang sauce and mix everything before eating.",
    ],
  },
  {
    id: "d20",
    name: "Vegan Chickpea Curry",
    type: "dinner",
    calories: 400,
    protein_g: 16,
    carbs_g: 54,
    fat_g: 12,
    tags: ["vegan", "gluten-free"],
    allergens: [],
    cuisines: ["Indian", "British"],
    description: "Hearty chickpea curry with coconut milk, ginger and warming spices.",
    steps: [
      "Sauté diced onion, garlic and ginger in oil until golden.",
      "Add curry powder, garam masala and turmeric; toast 1 minute.",
      "Add 400g canned chickpeas and 400g canned tomatoes; stir well.",
      "Pour in 200ml coconut milk; simmer 20 minutes.",
      "Add baby spinach; cook until wilted. Serve with rice.",
    ],
  },
  {
    id: "d21",
    name: "French Ratatouille",
    type: "dinner",
    calories: 320,
    protein_g: 7,
    carbs_g: 36,
    fat_g: 15,
    tags: ["vegan", "gluten-free"],
    allergens: [],
    cuisines: ["French", "Mediterranean"],
    description: "Slow-cooked Provençal vegetable stew with tomatoes, courgette and herbs.",
    steps: [
      "Dice aubergine, courgette, peppers and onion into even chunks.",
      "Sauté onion and garlic in olive oil; add peppers and aubergine.",
      "Add courgette, canned tomatoes, thyme, basil and seasoning.",
      "Simmer covered on low heat for 40 minutes, stirring occasionally.",
      "Serve warm or at room temperature with crusty bread.",
    ],
  },
];

export const MEAL_LIBRARY: Meal[] = [...BREAKFAST, ...LUNCH, ...DINNER];

export const MEALS_BY_TYPE: Record<MealType, Meal[]> = {
  breakfast: BREAKFAST,
  lunch: LUNCH,
  dinner: DINNER,
};
