import { useState } from "react";
import { Capacitor } from "@capacitor/core";

const SOURCES = [
  {
    label: "USDA FoodData Central",
    url: "https://fdc.nal.usda.gov/",
    desc: "Nutritional composition data for foods",
  },
  {
    label: "FDA Nutrition Facts Label",
    url: "https://www.fda.gov/food/nutrition-facts-label/how-understand-and-use-nutrition-facts-label",
    desc: "U.S. reference values for daily nutrients",
  },
  {
    label: "Health Canada — Canada's Food Guide",
    url: "https://food-guide.canada.ca/en/",
    desc: "Canadian dietary guidance and recommendations",
  },
  {
    label: "NIH Dietary Reference Intakes",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK56068/",
    desc: "Macro and calorie reference intakes by age/sex",
  },
  {
    label: "Mifflin-St Jeor BMR formula",
    url: "https://pubmed.ncbi.nlm.nih.gov/2305711/",
    desc: "Validated formula used for calorie target calculations",
  },
];

function openUrl(url: string) {
  if (Capacitor.isNativePlatform()) {
    import("@capacitor/browser").then(({ Browser }) => {
      void Browser.open({ url });
    });
  } else {
    window.open(url, "_blank", "noopener,noreferrer");
  }
}

/** Full disclaimer panel content (shared between inline and standalone modes) */
function DisclaimerPanel({ showSources }: { showSources: boolean }) {
  const [sourcesOpen, setSourcesOpen] = useState(false);

  return (
    <>
      <p className="font-semibold text-[var(--text)]">⚠️ Nutrition disclaimer</p>
      <p className="mt-1">
        Nutrition values are{" "}
        <span className="font-medium">estimates generated by AI</span> and may vary
        depending on ingredient brands, preparation methods, and portion sizes. They
        are provided for general informational purposes only and are{" "}
        <span className="font-medium">
          not a substitute for professional medical or dietitian advice.
        </span>{" "}
        Calorie targets are calculated using the Mifflin-St Jeor formula and standard
        activity multipliers. Always consult a qualified health professional for
        dietary or medical concerns.
      </p>

      {showSources ? (
        <div className="mt-3">
          <button
            type="button"
            onClick={() => setSourcesOpen((v) => !v)}
            className="flex items-center gap-1 font-semibold text-[var(--green)] underline underline-offset-2"
            aria-expanded={sourcesOpen}
          >
            {sourcesOpen ? "▾ Hide" : "▸ View"} nutrition sources &amp; references
          </button>

          {sourcesOpen ? (
            <ul className="mt-3 space-y-2.5">
              {SOURCES.map((s) => (
                <li key={s.url} className="flex flex-col gap-0.5">
                  <button
                    type="button"
                    onClick={() => openUrl(s.url)}
                    className="text-left font-semibold text-[var(--green)] underline underline-offset-2"
                  >
                    {s.label}
                  </button>
                  <span className="text-[11px] text-[var(--gray)]">{s.desc}</span>
                </li>
              ))}
            </ul>
          ) : null}
        </div>
      ) : null}
    </>
  );
}

type Props = {
  /**
   * When true, renders a small inline link "ⓘ Nutrition estimates • Sources & disclaimer"
   * that expands the full panel on tap. This is the preferred placement directly below
   * nutrition values. Defaults to false (full panel always visible).
   */
  inline?: boolean;
  /** Show the expandable sources list. Only applies when the panel is visible. Default true. */
  showSources?: boolean;
  className?: string;
};

export function NutritionDisclaimer({
  inline = false,
  showSources = true,
  className = "",
}: Props) {
  const [panelOpen, setPanelOpen] = useState(false);

  if (inline) {
    return (
      <div className={className}>
        <button
          type="button"
          onClick={() => setPanelOpen((v) => !v)}
          className="flex items-center gap-1 text-[11px] text-[var(--gray)] underline underline-offset-2 hover:text-[var(--green)] transition-colors"
          aria-expanded={panelOpen}
        >
          <span>ⓘ</span>
          <span>Nutrition estimates • Sources &amp; disclaimer</span>
          <span className="text-[10px]">{panelOpen ? "▴" : "▾"}</span>
        </button>

        {panelOpen ? (
          <aside className="mt-2 rounded-2xl border border-[var(--border)] bg-[var(--cream)] p-4 text-xs leading-relaxed text-[var(--gray)]">
            <DisclaimerPanel showSources={showSources} />
          </aside>
        ) : null}
      </div>
    );
  }

  return (
    <aside
      className={`rounded-2xl border border-[var(--border)] bg-[var(--cream)] p-4 text-xs leading-relaxed text-[var(--gray)] ${className}`}
    >
      <DisclaimerPanel showSources={showSources} />
    </aside>
  );
}
